### PR TITLE
Revert "removing protocol relative url"

### PR DESCRIPTION
**Pull request by asennikov**
Reverts asennikov/ember-g-map#43

### CODE REVIEW

**Comment by asennikov** [comment]
Heu @mansona, I've merged your PR but then realised, that we already have support for setting protocol directly on demand. 

See this old PR for details - https://github.com/asennikov/ember-g-map/pull/26 I'll add this info to docs.

**Comment by asennikov** [comment]
Actually, we already have it noted here - https://github.com/asennikov/ember-g-map#configuration

**Comment by mansona** [comment]
@asennikov that seems like an extraneous configuration now that protocol relative urls are considered an anti-pattern? maybe having the *default* be https would be better? 

Would you like me to put together a PR that puts the default as https?

**Comment by asennikov** [comment]
Yeah, you're probably right. Let's do another PR, but let's just make it though it won't break apps that are already setting `src` directly there.

**Pull request merged**
