### PR TITLE
Remove ember-try

### PR DESCRIPTION
**Pull request by hbrysiewicz**
Remove deprecation warning about unnecessary inclusion of `ember-try` in `package.json`

### CODE REVIEW

**Comment by hbrysiewicz** [comment]
The cache on Travis needs to be cleared I believe for a rerun - don't have access to do this..

**Comment by asennikov** [comment]
Hmm, can you share that deprecation warning? I can't see it myself for some reason, also it seems that https://github.com/ember-cli/ember-try has updated their API, I think we should adjust travis.yml to follow latest config syntax.

**Comment by hbrysiewicz** [comment]
I just cloned the repository and ran `ember test` and it shows up. 
screen shot 2016-07-20 at 11 16 38 am

The travis test needs to be rerun with cache cleared first and it will pass. This is a one line PR.

**Comment by asennikov** [comment]
Looks like `ember-cli` includes `ember-try` starting from v2.6.0 and we still have v2.5.0 in this project. It warns you because you probably already have 2.6 installed locally. So to make this PR pass you also need to update ember-cli version of this project.

**Comment by hbrysiewicz** [comment]
This now includes an upgrade to v2.6.2

**Comment by asennikov** [comment]
awesome!

**Pull request merged**
