### PR TITLE
keep the map fit to markers

### PR DESCRIPTION
**Pull request by ofridagan**
I had to make this small change to keep the map fit to markers while they change.
My use-case is a filtered list of people shown as markers on the map.. so I want the map to always show all markers.
I could maybe make this functionality togglable with an option flag like 'shouldKeepFitToMarkers'...

### CODE REVIEW

**Comment by asennikov** [comment]
Nice! I've thought about it before, but had no chance to actually implement it.

Probably, yes, better make it optional, 'cause I have use-case in one of my apps where I need map to fit to initial markers only.

P.S. There are some failing tests, better fix them too before merge.

**Comment by ofridagan** [comment]
Hi, I added a property 'markersFitMode' and also updated the README.
I also kept the original 'shouldFit' property which makes it backward compatible.

as for the tests, can you please help?
I tried running 'ember test' on your master branch and got:
```
Rule "disallowVar" is already registered
AssertionError: Rule "disallowVar" is already registered
    at NodeConfiguration.Configuration.registerRule (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:864:5)
    at NodeConfiguration.Configuration._loadAdditionalRule (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:825:10)
    at NodeConfiguration.<anonymous> (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/node-configuration.js:213:61)
    at Array.forEach (native)
    at NodeConfiguration._loadAdditionalRule (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/node-configuration.js:211:61)
    at NodeConfiguration.<anonymous> (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:502:18)
    at Array.forEach (native)
    at NodeConfiguration.Configuration._processConfig (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:501:33)
    at NodeConfiguration.Configuration._loadPreset (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/configuration.js:748:10)
    at NodeConfiguration._loadPreset (/Users/ofri/home-dev/ember-g-map/node_modules/ember-suave/node_modules/broccoli-jscs/node_modules/jscs/lib/config/node-configuration.js:163:41)
```

**Comment by asennikov** [comment]
Sure, I'll take a look this weekend.

**Comment by asennikov** [comment]
Hey @ofridagan, I've created PR to your master branch which fixes tests and adjusts some behaviour. If you okay with it - just merge it to your branch and then I can merge it here.

**Comment by ofridagan** [comment]
merged. Thanks!

**Pull request merged**
