### PR TITLE
Clustering support using markerclustererplus

### PR DESCRIPTION
**Pull request by sprocketc**
#### Changes

I tried to follow your coding style without changing your components and made the following additions to support clustering:
- A `g-map-clusterer` component is added. It should be used inside a `g-map` component with context set, just like the markers. You can set the `options` param to customize the clusterer ([available options](https://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclustererplus/docs/reference.html#MarkerClustererOptions)). The clusterer also supports the `live` mode and repaints itself when the markers change.
- A `g-map-cluster-marker` component is added. It extends the `g-map-marker` component and should be used inside a `g-map-clusterer` component with context set.
- A default blueprint is added and the index.js changed to import the clustering library dependency.
#### Usage

```
{{#g-map as |context|}}
  {{#g-map-clusterer context as |clustererContext|}}
    {{g-map-cluster-marker clustererContext}}
  {{/g-map-clusterer}}
{{/g-map}}
```

You can also mix clustered markers with default markers without issues (i hope) like the example below:

```
{{#g-map as |context|}}

  {{#g-map-clusterer context as |clustererContext|}}
    {{g-map-cluster-marker clustererContext}}
  {{/g-map-clusterer}}

  {{g-map-marker context}}

{{/g-map}}
```
### Todo
- More tests?
- Documentation
- I think i should make the import of the clustering lib optional using `ENV['g-map']`

### CODE REVIEW

**Comment by asennikov** [comment]
Looks good so far :+1: 

For the next steps:
> More tests?

Yeah, I'd like to have this functionality covered with tests.
I would really like to have integration tests covering this addon instead of too detailed functional tests available now, but I have no idea how to test that something really appeared on google map. So, I think  we should go with current testing approach unless you have some better ideas.

> Documentation

I can add it later, or you can just add section to README yourself, you have covered it mostly with notes to this PR.

> I think i should make the import of the clustering lib optional using ENV['g-map']

Yes, that would be better.

**Comment by sprocketc** [comment]
About the optional import, i think it should be an array of libraries. That way we can add more dependencies in the future without adding another property for each one. Something like 
`addons: ['clustering', 'richmarker', 'etc']` Not sure about the name ('libraries' is taken).

About the tests, i already tried to write some unit tests but `MarkerClusterer` function is globally defined in the library and i have an issue with `stub`. I' ll give it another shot later.

**Comment by asennikov** [comment]
> About the optional import, i think it should be an array of libraries. That way we can add more dependencies in the future without adding another property for each one. Something like 
addons: ['clustering', 'richmarker', 'etc'] Not sure about the name ('libraries' is taken).
Maybe `extensions`?

> About the tests, i already tried to write some unit tests but MarkerClusterer function is globally defined in the library and i have an issue with stub. I'll give it another shot later.
Yeah, however sinon should work, `google.maps` is globally defined too and it works well with it.

**Comment by sprocketc** [comment]
Optional import of external libraries is done.
You can choose to import the clustering lib by adding the following to your `ember-cli-build.js`

```
module.exports = function(defaults) {
  var app = new EmberApp(defaults, {
    gMap: {
      extensions: ['clustering']
    }
  });
  return app.toTree();
};
```

**Comment by asennikov** [comment]
Nice, if you want me to help you with tests - I can do a PR to your fork.

**Comment by Gaelan** [comment]
Sorry for the drive-by comment, but what's the status of this?

**Comment by steveszc** [comment]
@Gaelan I think the feature was working, but was never merged due to a lack of test coverage. It doesn't look like anyone stepped up to write proper tests for the feature. 

I'm generally opposed to merging this, though. This PR would add a new bower dependency without any kind of tree shaking to make it optional for users that don't require clustering. I don't think marker clustering is a common enough usecase to package this into the main ember-g-map addon.

That being said, there's nothing to stop you from forking this PR or writing your own marker-clusterer component in your own app. This kind of think could also be published as an addon intended to be user with ember-g-map.

**Pull request closed without merging**
