### PR TITLE
Polyline options for Routes

### PR DESCRIPTION
**Pull request by asennikov**
Some better styling for polylines produced by {{g-map-route}} and {{g-map-address-route}} components.
Available options:
* strokeColor
* strokeWeight
* strokeOpacity
* zIndex

image

### CODE REVIEW

**Comment by kirantpatil** [comment]
Sir, is there availability to show distance in km of the route ?

**Comment by asennikov** [comment]
@kirantpatil currently there's no such option. 

But looks like Google Maps API provides an ability to calculate total distance by summing legs of the route https://developers.google.com/maps/documentation/javascript/directions#Routes 
So it would be better to open another issue for this feature request or if you feel like you can handle this - a PR :wink:

**Comment by kirantpatil** [comment]
@asennikov our developer is junior and I will assist my best and at the same time it may require your guidance as well.

What is your opinion shall we go ahead or will you or anyone from community take it up ?

**Comment by asennikov** [comment]
We should probably start with moving this conversation to a separate Issue in this repository, since current PR is about a bit different feature.

**Pull request merged**
